#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
    echo "Setting up for Mac..."
    sleep 1
    ~/.dev-machine/setups/mac
fi

 ~/.dev-machine/setups/zprezto
 ~/.dev-machine/setups/ruby
 ~/.dev-machine/setups/nodejs
 ~/.dev-machine/setups/docker
 ~/.dev-machine/setups/vscode

 echo "✅ Done! Please open a new terminal window for changes to take effect."